### ISSUE TITLE
extension proposal

### ISSUE THREAD

**Issue by stemangiola** [mtmorgan/cellxgenedp#10]
Hello @mtmorgan,

I am doing an institutional project around Human Cell Atlas and I was wondering whether this is something that you would be interested in integrating within this package (rather than me creating a new one). 

I have harmonised the whole human database, so to make it queriable (at the cell level) through metadata. 

For example, with the metadata (harmonised including dataset, sample and cell information)

```r
# A tibble: 28,981,744 × 44
   sample___    assay assay…¹ cell_…² cell_…³ devel…⁴ devel…⁵ disease disea…⁶ ethni…⁷ ethni…⁸ file_id file_…⁹ is_pr…˟ organ…˟ organ…˟
   <fct>        <fct> <fct>   <fct>   <fct>   <fct>   <fct>   <fct>   <fct>   <fct>   <fct>   <chr>   <fct>   <lgl>   <fct>   <fct>  
 1 D17PrPzF_Vi… 10x … EFO:00… basal … CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
 2 D17PrPzF_Vi… 10x … EFO:00… basal … CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
 3 D17PrPzF_Vi… 10x … EFO:00… lumina… CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
 4 D17PrPzF_Vi… 10x … EFO:00… lumina… CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
 5 D17PrPzF_Vi… 10x … EFO:00… basal … CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
 6 D17PrPzF_Vi… 10x … EFO:00… basal … CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
 7 D17PrPzF_Vi… 10x … EFO:00… basal … CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
 8 D17PrPzF_Vi… 10x … EFO:00… basal … CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
 9 D17PrPzF_Vi… 10x … EFO:00… lumina… CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
10 D17PrPzF_Vi… 10x … EFO:00… basal … CL:000… 31-yea… HsapDv… normal  PATO:0… Europe… HANCES… 00d626… /vast/… FALSE   Homo s… NCBITa…
# … with 28,981,734 more rows, 28 more variables: sex <fct>, sex_ontology_term_id <fct>, tissue <fct>,
#   tissue_ontology_term_id <fct>, dataset_id <chr>, collection_id <chr>, cell_count <int>, dataset_deployments <chr>,
#   is_primary_data.y <chr>, is_valid <lgl>, linked_genesets <lgl>, mean_genes_per_cell <dbl>, name <chr>, published <lgl>,
#   revision <int>, schema_version <chr>, tombstone <lgl>, x_normalization <chr>, created_at.x <date>, published_at <date>,
#   revised_at <date>, updated_at.x <date>, filename <chr>, filetype <chr>, s3_uri <chr>, user_submitted <lgl>, created_at.y <date>,
#   updated_at.y <date>, and abbreviated variable names ¹​assay_ontology_term_id, ²​cell_type, ³​cell_type_ontology_term_id,
#   ⁴​development_stage, ⁵​development_stage_ontology_term_id, ⁶​disease_ontology_term_id, ⁷​ethnicity, ⁸​ethnicity_ontology_term_id, …
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names
```

The query looks like

```r
metadata |> 
filter(
    ethnicity == "African", 
    assay |> str_detect("10x"), 
    tissue == "lung parenchyma", 
    cell_type |> str_detect("CD4")
) |> 
    get_SingleCellExperiment()

```

The output looks like

```r
class: SingleCellExperiment 
dim: 60661 1571 
metadata(7): X_normalization batch_condition ... schema_version title
assays(1): X
rownames(60661): TSPAN6 TNMD ... RP11-175I6.6 PRSS43P
rowData names(0):
colnames(1571): ACAGCCGGTCCGTTAA_F02526_6661ab3a-792a-4682-b58c-4afb98b2c016
  GGGAATGAGCCCAGCT_F02526_6661ab3a-792a-4682-b58c-4afb98b2c016 ... TACAACGTCAGCATTG_SC84_6661ab3a-792a-4682-b58c-4afb98b2c016
  CATTCGCTCAATACCG_F02526_6661ab3a-792a-4682-b58c-4afb98b2c016
colData names(45): .sample assay ... created_at.y updated_at.y
```

For the moment the data sits locally for the institute to query, but that could go remote.

**Comment by mtmorgan** [comment]
Wow that looks great @stemangiola ! I think this would be better as a stand-alone package. Would the data be made available (maybe as a sqlite table, with dbplyr interface?) on ExperimentHub? Or hosted more dynamically?

Looks really great!

**Comment by mtmorgan** [comment]
@stemangiola I'd be very interested in hearing more of what you've done, e.g., if you have a repository, or just a description...

**Comment by stemangiola** [comment]
Thanks @mtmorgan,



> Would the data be made available

The query system serves the local community, but if there is interest in making this public (and hopefully resulting in an interesting publication), my idea is to do so. We have to see the best public (free) storage/query platform


> maybe as a sqlite table, with dbplyr interface

Yes, it's a very elegant choice (and easy given the relatively simple relations in the data), I had thought about that, but this is possible only if I will find some help as I don't have time now to develop that.

At the moment it is a file-based "database". to make a file-based database public I assume we could use some network pointers. I'm not sure if `ExperimentHub` support backend query.

If you have any suggestions, please feel free!



> I'd be very interested in hearing more of what you've done

It would be nice to have a chat. Basically, I have done a first-level harmonization of metadata types, sample ID, and count representation. 

> if you have a repository, or just a description

There is a functional package that lives on our servers

**Comment by LiNk-NY** [comment]
For completeness: https://github.com/stemangiola/HCAquery
This is great Stefano!
Best,
Marcel
