### ISSUE TITLE
should `filter` be re-exported?

### ISSUE THREAD

**Issue by LiNk-NY** [mtmorgan/cellxgenedp#11]
Hi Martin, @mtmorgan 

The code as intended does not work if `dplyr` is not loaded. Should `filter` be re-exported? 

```r
> library(cellxgenedp)
> datasets(db()) |>
   filter(
     facets_filter(assay, "ontology_term_id", "EFO:0009922"),
     facets_filter(ethnicity, "label", "African American"),
     facets_filter(sex, "label", "female")
   )
Error in facets_filter(ethnicity, "label", "African American") : 
  object 'ethnicity' not found
```

**Comment by mtmorgan** [comment]
It's kind of weird; the examples and vignettes work because they explicitly `library(dplyr)` and the objects do not necessarily have to be manipulated w/ dplyr. Nonetheless, i moved dplyr from Imports: to Depends: so it'll be there (and masking `stats::filter()`) for the user....
