### ISSUE TITLE
No dataset to visualise with datasets_visualize()

### ISSUE THREAD

**Issue by lgatto** [mtmorgan/cellxgenedp#15]
In the vignette, this code chunk doesn't filter/visualise anything, as there aren't any CXG types

```
selected_files |>
    filter(filetype == "CXG") |>
    slice(1) |> # visualize a single dataset
    datasets_visualize()
```

```
> pull(selected_files, filetype) |> table()

H5AD  RDS 
  34   34 
```

**Comment by mtmorgan** [comment]
Thanks; the process for visualization now just requires a `dataset_id`. In the context of the vignette, one can 

```
african_american_female |>
    ## use criteria to identify a single dataset, then visualize
    slice(1) |>
    datasets_visualize()
```
without having to find files associated with the dataset.

This is fixed in Bioc 3.18 / devel at version 1.6.1 / 1.7.1, and from this repository using `remotes::install_github()`.
