### ISSUE TITLE
`x_normalisation` column not available anymore?

### ISSUE THREAD

**Issue by stemangiola** [mtmorgan/cellxgenedp#16]
I believe in some previous version there was a column `x_normalisation` that had values cush as "log", "square_root".

Now I only see a a related column with mostly NA (tagging @myushen)
```r
  x_approximate_distribution     n
  <fct>                      <int>
1 NORMAL                       167
2 COUNT                        392
3 NA                         50646
```

I am missing something?

Thanks!

**Comment by mtmorgan** [comment]
Likely this is related to upstream changes in CELLxGENE, in particular formalizing the ['Discover' API](https://api.cellxgene.cziscience.com/curation/ui/). These changes were introduced in cellxgenedp in [version 1.6](https://mtmorgan.github.io/cellxgenedp/news/index.html#cellxgenedp-16-1).

My [summary of changes](https://mtmorgan.github.io/cellxgenedp/articles/a_using_cellxgenedp.html#api-changes) does not list `x_normalisation`, but I'm not sure how reliable my summary is. The original API is no longer available.
