### ISSUE TITLE
Infer dataset_id from the downloading URL

### ISSUE THREAD

**Issue by YXC33** [mtmorgan/cellxgenedp#17]
Hi, how can I get the dataset_id if I only have the downloading URL in the Cellxgene?
For example:
![微信截图_20240918144820](https://github.com/user-attachments/assets/448b92ac-2e99-4209-8af2-89488b0cc37e)
How can I infer the dataset_id if I only have this URL?
URL: https://datasets.cellxgene.cziscience.com/d39144df-fa59-4b63-b07b-9b34613b5c84.rds
dataset_id: 37b21763-7f0f-41ae-9001-60bad6e2841d

Thanks a lot in advance!

**Comment by mtmorgan** [comment]
I believe URL id is the `dataset_version_id`, and the relation between `dataset_id` and `dataset_version_id` is in the table returned by `datasets()`
```r
library(dplyr)
d = datasets()
d |>
    filter(dataset_version_id == "d39144df-fa59-4b63-b07b-9b34613b5c84") |> 
    select(dataset_id, dataset_version_id)
## # A tibble: 1 × 2
##   dataset_id                           dataset_version_id                  
##   <chr>                                <chr>                               
## 1 37b21763-7f0f-41ae-9001-60bad6e2841d d39144df-fa59-4b63-b07b-9b34613b5c84

**Comment by YXC33** [comment]
Thank you so much! It is really what I am looking for!
